# Tags: 6.0-alpine-amd64, 6.0-alpine3.14-amd64, 6.0.0-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/runtime:6.0.0-alpine3.14-amd64
