# Tags: 3.1-alpine, 3.1-alpine3.14, 3.1.21-alpine3.14
FROM mcr.microsoft.com/dotnet/runtime:3.1-alpine
FROM mcr.microsoft.com/dotnet/runtime:3.1-alpine3.14
FROM mcr.microsoft.com/dotnet/runtime:3.1.21-alpine3.14
