# Tags: 5.0-alpine-amd64, 5.0-alpine3.14-amd64, 5.0.12-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/runtime:5.0.12-alpine3.14-amd64
