# Tags: 3.1-alpine-arm64v8, 3.1-alpine3.14-arm64v8, 3.1.21-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:3.1-alpine-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:3.1-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:3.1.21-alpine3.14-arm64v8
