# Tags: 6.0-alpine3.14-arm64v8, 6.0.0-alpine3.14-arm64v8, 6.0-alpine-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:6.0.0-alpine3.14-arm64v8
FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine-arm64v8
