# Tags: 6.0-windowsservercore-ltsc2019, 6.0.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/runtime:6.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/runtime:6.0.0-windowsservercore-ltsc2019
